config-version = 2
after-startup-command = []
start-at-login = false
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

persistent-workspaces = ["J", "K", "L"]
default-root-container-layout = "tiles"
default-root-container-orientation = "auto"
accordion-padding = 0
[gaps]
    inner.horizontal = 0
    inner.vertical = 0
    outer.left = 0
    outer.bottom = 0
    outer.top = 0
    outer.right = 0

[mode.main.binding]
    alt-cmd-ctrl-shift-u = ["flatten-workspace-tree", "layout h_tiles", "focus --dfs-index 0", "move left"]
    alt-cmd-ctrl-shift-i = ["flatten-workspace-tree", "layout v_accordion", "focus --dfs-index 0", "move left", "focus-back-and-forth"]
    alt-cmd-ctrl-shift-o = ["flatten-workspace-tree", "layout h_accordion"]
    alt-cmd-ctrl-shift-p = ["focus --dfs-index 0", "move right", "focus-back-and-forth", "move left", "move left"]
    alt-cmd-ctrl-shift-j = "exec-and-forget open -a \"Zen Browser\""
    alt-cmd-ctrl-shift-k = "exec-and-forget open -a Ghostty"
    alt-shift-j = "move-node-to-workspace --focus-follows-window J"
    alt-shift-k = "move-node-to-workspace --focus-follows-window K"
    alt-shift-l = "move-node-to-workspace --focus-follows-window L"
    alt-shift-tab = "move-node-to-monitor --focus-follows-window --wrap-around next"
    alt-j = "workspace J"
    alt-k = "workspace K"
    alt-l = "workspace L"
    alt-tab = "workspace-back-and-forth"
    alt-equal = "resize smart +50"
    alt-minus = "resize smart -50"
    alt-t = "layout floating tiling"
    alt-v = "layout vertical horizontal"
    alt-cmd-ctrl-shift-h = "exec-and-forget sup | choose"
    alt-cmd-ctrl-shift-1 = "exec-and-forget PICKER=choose run-mp3"

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = 'move-node-to-workspace J'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace K'
